#ifndef _CONFIG_H_
#define _CONFIG_H_

#include <stm32f767xx.h>

#define MINI_PC_COMMUNICATION_INTERFACE		SPI3

#define MINI_PC_COMMUNICATION_RECEIVER_DMA_STREAM	DMA1_Stream2
#define MINI_PC_COMMUNICATION_RECEIVER_DMA_CONTROLLER		DMA1
#define MINI_PC_COMMUNICATION_RECEIVER_DMA_STREAM_CHANNEL	(0)
#define MINI_PC_COMMUNICATION_RECEIVER_DMA_CONFIGURATION	((MINI_PC_COMMUNICATION_RECEIVER_DMA_STREAM_CHANNEL << DMA_SxCR_CHSEL_Pos) | \
															 DMA_SxCR_MINC | DMA_SxCR_CIRC)
#define MINI_PC_COMMUNICATION_TRANSMITTER_DMA_STREAM	DMA1_Stream5
#define MINI_PC_COMMUNICATION_TRANSMITTER_DMA_CONTROLLER	DMA1
#define MINI_PC_COMMUNICATION_TRANSMITTER_DMA_STREAM_CHANNEL	(0)
#define MINI_PC_COMMUNICATION_TRANSMITTER_DMA_CONFIGURATION		((MINI_PC_COMMUNICATION_TRANSMITTER_DMA_STREAM_CHANNEL << DMA_SxCR_CHSEL_Pos) | \
																 DMA_SxCR_MINC | DMA_SxCR_TCIE | DMA_SxCR_DIR_0)

#endif	//	_CONFIG_H_
